import { Check, Menu, ShoppingBag, User } from "lucide-react";
import type { ThemePreview, PreviewProps } from "../types";
import { getLandingCopy, readableOn, Rating } from "../utils";

function Shell({ children, palette }: { children: React.ReactNode; palette: PreviewProps["palette"] }) { return <div className="min-h-[620px] p-6" style={{ backgroundColor: palette.background, color: palette.textPrimary }}>{children}</div>; }
function Landing({ palette, websiteType }: PreviewProps) { const copy = getLandingCopy(websiteType); return <Shell palette={palette}><nav className="flex items-center justify-between rounded-3xl border p-4" style={{ backgroundColor: palette.card, borderColor: palette.border }}><span className="font-bold">Local Goods</span><button className="rounded-full px-5 py-2 text-sm font-semibold" style={{ backgroundColor: palette.primary, color: readableOn(palette.primary) }}>{copy.cta}</button></nav><section className="mt-8 grid gap-6 lg:grid-cols-[1fr_0.9fr]"><div className="rounded-[2rem] p-8" style={{ backgroundColor: palette.surface }}><p className="text-sm font-semibold" style={{ color: palette.primary }}>{copy.kicker}</p><h3 className="mt-3 text-5xl font-black leading-[1] tracking-[-0.05em]">{copy.title}</h3><p className="mt-5 max-w-md text-base leading-7" style={{ color: palette.textSecondary }}>{copy.kicker}. Built for discovery, trust, and fast conversion.</p><div className="mt-8 flex flex-wrap gap-2">{copy.items.map((item) => <span key={item} className="rounded-full px-3 py-1 text-xs" style={{ backgroundColor: palette.card, color: palette.textSecondary }}>{item}</span>)}</div></div><div className="grid gap-4">{["Featured", "Best seller", "New arrival"].map((item, i) => <div key={item} className="rounded-[2rem] border p-5" style={{ backgroundColor: palette.card, borderColor: palette.border }}><div className="mb-5 h-28 rounded-3xl" style={{ background: `linear-gradient(135deg, ${palette.primary}, ${palette.secondary}, ${palette.accent})` }} /><p className="font-bold">{item}</p><p className="text-sm" style={{ color: palette.textSecondary }}>${i === 0 ? 29 : i === 1 ? 49 : 19}</p></div>)}</div></section></Shell>; }
function Dashboard({ palette }: PreviewProps) { return <Shell palette={palette}><h3 className="text-4xl font-black tracking-[-0.04em]">Store operations</h3><div className="mt-6 grid gap-4 md:grid-cols-3">{["Orders", "Revenue", "Products"].map((item, i) => <div key={item} className="rounded-3xl border p-6" style={{ backgroundColor: palette.card, borderColor: palette.border }}><p style={{ color: palette.textSecondary }}>{item}</p><p className="mt-3 text-4xl font-black">{i === 0 ? 284 : i === 1 ? "$12k" : 92}</p></div>)}</div><div className="mt-4 rounded-3xl border p-6" style={{ backgroundColor: palette.card, borderColor: palette.border }}><div className="grid gap-3">{["Latte kit", "Template bundle", "Limited menu"].map((item) => <div key={item} className="flex items-center justify-between rounded-2xl p-4" style={{ backgroundColor: palette.surface }}><span>{item}</span><Check className="h-4 w-4" style={{ color: palette.success }} /></div>)}</div></div></Shell>; }
function Login({ palette }: PreviewProps) { return <Shell palette={palette}><div className="grid min-h-[560px] place-items-center"><div className="w-full max-w-sm rounded-[2rem] border p-7" style={{ backgroundColor: palette.card, borderColor: palette.border }}><ShoppingBag className="mb-6 h-10 w-10" style={{ color: palette.primary }} /><h3 className="text-3xl font-black">Welcome back</h3><input className="mt-6 w-full rounded-2xl border px-4 py-3" placeholder="Email" /><button className="mt-4 w-full rounded-full py-3 font-semibold" style={{ backgroundColor: palette.primary, color: readableOn(palette.primary) }}>Continue</button></div></div></Shell>; }
function Pricing({ palette }: PreviewProps) { return <Shell palette={palette}><h3 className="text-center text-5xl font-black tracking-[-0.04em]">Choose package</h3><div className="mt-8 grid gap-4 md:grid-cols-3">{["Solo", "Shop", "Market"].map((item, i) => <div key={item} className="rounded-[2rem] border p-6" style={{ backgroundColor: palette.card, borderColor: palette.border }}><p className="font-bold">{item}</p><p className="mt-5 text-4xl font-black">${i === 0 ? 9 : i === 1 ? 29 : 79}</p></div>)}</div></Shell>; }
function Product({ palette }: PreviewProps) { return <Shell palette={palette}><div className="grid min-h-[560px] place-items-center"><div className="w-full max-w-sm rounded-[2rem] border p-4" style={{ backgroundColor: palette.card, borderColor: palette.border }}><div className="h-64 rounded-[1.5rem]" style={{ background: `linear-gradient(135deg, ${palette.primary}, ${palette.secondary})` }} /><h3 className="mt-5 text-2xl font-black">Signature Pack</h3><Rating palette={palette} /><button className="mt-5 w-full rounded-full py-3 font-semibold" style={{ backgroundColor: palette.primary, color: readableOn(palette.primary) }}>Add to cart</button></div></div></Shell>; }
function MobileApp({ palette }: PreviewProps) { return <Shell palette={palette}><div className="grid min-h-[560px] place-items-center"><div className="w-[300px] rounded-[2.5rem] border-8 border-black p-4" style={{ backgroundColor: palette.card }}><div className="flex justify-between"><Menu /><User /></div><h3 className="mt-8 text-3xl font-black">Shop</h3><div className="mt-5 grid gap-3">{["Orders", "Products"].map((item) => <div key={item} className="rounded-2xl p-4" style={{ backgroundColor: palette.surface }}>{item}</div>)}</div></div></div></Shell>; }

export const commerceWarmTheme: ThemePreview = { id: "commerce-warm", label: "Commerce Warm", vibeIds: ["coffee-warm", "indonesian-umkm", "marketplace-bright", "bold-startup", "education-friendly"], render: { "Landing Page": Landing, Dashboard, "Login Page": Login, "Pricing Page": Pricing, "Product Card": Product, "Mobile App": MobileApp } };
