import { BarChart3, Check, Home, Lock, Package, User } from "lucide-react";
import type { ThemePreview, PreviewProps } from "../types";
import { getLandingCopy, readableOn, Rating } from "../utils";

function Frame({ children }: { children: React.ReactNode; palette: PreviewProps["palette"] }) {
  return <div className="min-h-[620px] bg-[#080706] p-6 font-serif text-[#fff9ec]">{children}</div>;
}

function Landing({ palette, websiteType, vibe }: PreviewProps) {
  const copy = getLandingCopy(websiteType);
  return <Frame palette={palette}><nav className="flex items-center justify-between border-b border-[#332b20] pb-5 text-sm"><span className="tracking-[0.4em] text-[#d6b56d]">VIBESITE</span><button className="border border-[#d6b56d] px-5 py-2 text-xs uppercase tracking-[0.25em] text-[#d6b56d]">{copy.cta}</button></nav><section className="grid gap-10 pt-14 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="text-xs uppercase tracking-[0.4em] text-[#d6b56d]">{vibe.name}</p><h3 className="mt-7 text-6xl leading-[0.95] tracking-[-0.06em] text-[#fff9ec]">{copy.title}</h3><p className="mt-6 max-w-md text-lg leading-8 text-[#b8aa92]">{copy.kicker}. Quiet luxury, slow rhythm, delicate lines, and product-led composition.</p></div><div className="min-h-[420px] border border-[#332b20] bg-[#191611] p-6"><div className="h-full" style={{ background: `linear-gradient(135deg, ${palette.primary}, ${palette.secondary})` }} /></div></section><div className="mt-10 grid gap-4 md:grid-cols-3">{copy.items.map((item) => <div key={item} className="border border-[#332b20] p-6"><Check className="mb-8 h-5 w-5 text-[#d6b56d]" /><p className="text-xl">{item}</p><p className="mt-3 text-sm leading-6 text-[#b8aa92]">Elegant hierarchy with restrained contrast.</p></div>)}</div></Frame>;
}
function Dashboard({ palette }: PreviewProps) { return <Frame palette={palette}><div className="grid gap-6 lg:grid-cols-[260px_1fr]"><aside className="border border-[#332b20] p-6"><p className="text-xs tracking-[0.4em] text-[#d6b56d]">ATELIER</p>{[Home, BarChart3, Package, User].map((Icon, i) => <div key={i} className="mt-8 flex items-center gap-3 text-[#b8aa92]"><Icon className="h-4 w-4" />Archive</div>)}</aside><main><h3 className="text-5xl tracking-[-0.05em]">Performance ledger</h3><div className="mt-8 grid gap-4 md:grid-cols-3">{["Revenue", "Clients", "Margin"].map((item, i) => <div key={item} className="border border-[#332b20] p-6"><p className="text-[#b8aa92]">{item}</p><p className="mt-6 text-4xl">{i === 0 ? "$84k" : i === 1 ? 128 : "32%"}</p></div>)}</div><div className="mt-4 border border-[#332b20] p-6"><div className="flex h-64 items-end gap-4">{[35, 58, 46, 75, 88, 64, 96].map((h, i) => <span key={i} className="flex-1" style={{ height: `${h}%`, backgroundColor: i === 4 ? palette.primary : "#332b20" }} />)}</div></div></main></div></Frame>; }
function Login({ palette }: PreviewProps) { return <Frame palette={palette}><div className="grid min-h-[560px] place-items-center"><div className="w-full max-w-sm border border-[#332b20] bg-[#12100d] p-8"><Lock className="mb-8 h-8 w-8 text-[#d6b56d]" /><h3 className="text-4xl tracking-[-0.05em]">Enter quietly.</h3><input className="mt-8 w-full border-b border-[#332b20] bg-transparent py-3 outline-none" placeholder="Email" /><input className="mt-4 w-full border-b border-[#332b20] bg-transparent py-3 outline-none" placeholder="Password" /><button className="mt-8 w-full py-3 text-sm uppercase tracking-[0.25em]" style={{ backgroundColor: palette.primary, color: readableOn(palette.primary) }}>Continue</button></div></div></Frame>; }
function Pricing({ palette }: PreviewProps) { return <Frame palette={palette}><h3 className="text-center text-6xl tracking-[-0.06em]">Membership</h3><div className="mt-10 grid gap-4 md:grid-cols-3">{["Essence", "Signature", "Patron"].map((p, i) => <div key={p} className="border border-[#332b20] p-8"><p className="text-[#d6b56d]">{p}</p><p className="mt-8 text-5xl">${i === 0 ? 19 : i === 1 ? 49 : 99}</p><button className="mt-10 w-full border border-[#d6b56d] py-3 text-xs uppercase tracking-[0.25em] text-[#d6b56d]">Select</button></div>)}</div></Frame>; }
function Product({ palette }: PreviewProps) { return <Frame palette={palette}><div className="grid min-h-[560px] place-items-center"><div className="w-full max-w-md border border-[#332b20] bg-[#12100d]"><div className="h-80" style={{ background: `linear-gradient(135deg, ${palette.primary}, ${palette.secondary})` }} /><div className="p-7"><p className="text-[#d6b56d]">Limited edition</p><h3 className="mt-2 text-4xl tracking-[-0.05em]">Refined UI Set</h3><div className="mt-4"><Rating palette={palette} /></div></div></div></div></Frame>; }
function MobileApp({ palette }: PreviewProps) { return <Frame palette={palette}><div className="grid min-h-[560px] place-items-center"><div className="w-[300px] rounded-[2rem] border border-[#332b20] bg-[#12100d] p-5"><p className="text-xs tracking-[0.4em] text-[#d6b56d]">PRIVATE</p><h3 className="mt-8 text-4xl tracking-[-0.06em]">Collection</h3><div className="mt-8 p-5" style={{ backgroundColor: palette.primary, color: readableOn(palette.primary) }}>Curated direction</div><div className="mt-4 border border-[#332b20] p-4">Export ready</div></div></div></Frame>; }

export const editorialLuxuryTheme: ThemePreview = { id: "editorial-luxury", label: "Editorial Luxury", vibeIds: ["luxury-brand", "elegant-editorial"], render: { "Landing Page": Landing, Dashboard, "Login Page": Login, "Pricing Page": Pricing, "Product Card": Product, "Mobile App": MobileApp } };
