import type { WebsiteType } from "./types";

export const websiteTypes: WebsiteType[] = [
  { id: "startup", name: "Startup Landing Page", description: "Conversion-focused page for a new product or company.", mood: ["ambitious", "clear", "modern", "confident"], layoutSuggestion: "Hero first, social proof, product value, feature grid, CTA bands.", componentSuggestion: "Strong hero CTA, logo wall, feature cards, testimonial blocks." },
  { id: "saas", name: "SaaS Website", description: "Product marketing website for subscription software.", mood: ["trustworthy", "scalable", "clean", "developer-friendly"], layoutSuggestion: "Structured sections, pricing clarity, feature comparison, product screenshots.", componentSuggestion: "Navbar, product cards, pricing cards, integrations grid." },
  { id: "portfolio", name: "Portfolio Personal", description: "Personal brand and work showcase.", mood: ["personal", "focused", "creative", "memorable"], layoutSuggestion: "Intro, selected work, skill proof, writing/contact sections.", componentSuggestion: "Project cards, timeline, skill chips, contact CTA." },
  { id: "dashboard", name: "Dashboard Admin", description: "Operational interface for monitoring and actions.", mood: ["efficient", "dense", "calm", "organized"], layoutSuggestion: "Sidebar navigation, metric cards, tables, charts, activity feed.", componentSuggestion: "Stat cards, filters, data table, progress widgets." },
  { id: "coffee", name: "Coffee Shop", description: "Warm local business website for menu, story, and visits.", mood: ["warm", "cozy", "earthy", "premium", "friendly"], layoutSuggestion: "Atmospheric hero, menu highlights, location, story, reservation CTA.", componentSuggestion: "Menu cards, image tiles, opening-hour badges, map panel." },
  { id: "education", name: "Education Website", description: "Learning platform, school, or course presentation.", mood: ["friendly", "clear", "accessible", "bright", "structured"], layoutSuggestion: "Course benefits, curriculum, instructor trust, outcomes.", componentSuggestion: "Course cards, progress modules, testimonial rows, FAQ." },
  { id: "fintech", name: "Fintech Website", description: "Finance product requiring trust and clarity.", mood: ["clean", "trustworthy", "secure", "professional", "calm"], layoutSuggestion: "Security proof, feature clarity, trust badges, transparent pricing.", componentSuggestion: "Security cards, stats, comparison table, compliance badges." },
  { id: "gaming", name: "Gaming Website", description: "Game, esport, or entertainment landing page.", mood: ["dark", "neon", "bold", "energetic", "futuristic"], layoutSuggestion: "Immersive hero, feature trailers, community CTA, event panels.", componentSuggestion: "Neon cards, countdowns, media grids, rank badges." },
  { id: "marketplace", name: "Marketplace", description: "Multi-vendor discovery and transaction site.", mood: ["bright", "useful", "trustworthy", "browseable"], layoutSuggestion: "Search first, categories, featured items, seller trust.", componentSuggestion: "Search bar, category chips, product grids, seller cards." },
  { id: "online-store", name: "Online Store", description: "Ecommerce storefront for products and conversion.", mood: ["commercial", "clean", "desirable", "direct"], layoutSuggestion: "Product-first hero, category shelves, offers, checkout confidence.", componentSuggestion: "Product cards, promo banners, cart buttons, review snippets." },
  { id: "agency", name: "Agency Website", description: "Creative or service agency presentation.", mood: ["sharp", "creative", "premium", "strategic"], layoutSuggestion: "Bold positioning, case studies, process, client proof.", componentSuggestion: "Case study cards, service tiles, marquee stats, inquiry CTA." },
  { id: "event", name: "Event Website", description: "Conference, workshop, concert, or launch event.", mood: ["timely", "energetic", "clear", "social"], layoutSuggestion: "Event promise, schedule, speakers, ticket CTA.", componentSuggestion: "Speaker cards, agenda rows, ticket cards, countdown badge." },
  { id: "blog", name: "Blog Personal", description: "Editorial writing, stories, and personal publishing.", mood: ["readable", "calm", "expressive", "focused"], layoutSuggestion: "Readable feed, featured essay, category filters, newsletter CTA.", componentSuggestion: "Article cards, author block, tag chips, newsletter panel." },
  { id: "product-showcase", name: "Product Showcase", description: "Visual presentation for a physical or digital product.", mood: ["polished", "desirable", "minimal", "premium"], layoutSuggestion: "Product visual first, benefits, specs, gallery, purchase CTA.", componentSuggestion: "Spec cards, image gallery, comparison blocks, CTA bars." },
  { id: "mobile-app", name: "Mobile App Landing Page", description: "Landing page for app downloads and feature discovery.", mood: ["friendly", "modern", "simple", "useful"], layoutSuggestion: "Phone mockup hero, app benefits, screenshots, app-store CTAs.", componentSuggestion: "Phone frame, feature rows, review cards, download buttons." },
  { id: "restaurant", name: "Restaurant Website", description: "Hospitality website for menu, location, and reservations.", mood: ["appetizing", "warm", "crafted", "welcoming"], layoutSuggestion: "Food photography hero, menu sections, reservation flow, reviews.", componentSuggestion: "Dish cards, reservation panel, chef story, location details." },
  { id: "digital-store", name: "Digital Product Store", description: "Store for templates, assets, courses, or downloads.", mood: ["creator-led", "useful", "sharp", "commercial"], layoutSuggestion: "Product grid, value proof, bundles, license clarity.", componentSuggestion: "Asset cards, bundle cards, license badges, quick preview." },
  { id: "course", name: "Course Website", description: "Education sales page for a specific course.", mood: ["credible", "motivating", "structured", "clear"], layoutSuggestion: "Outcome hero, modules, instructor credibility, enrollment CTA.", componentSuggestion: "Curriculum accordion, outcome cards, instructor bio, pricing block." },
  { id: "community", name: "Community Website", description: "Membership site for groups, forums, or creator communities.", mood: ["welcoming", "active", "social", "clear"], layoutSuggestion: "Community promise, member benefits, events, join CTA.", componentSuggestion: "Member cards, event list, benefit tiles, discussion previews." },
  { id: "nonprofit", name: "Nonprofit Website", description: "Mission-driven website for donations and awareness.", mood: ["human", "trustworthy", "hopeful", "direct"], layoutSuggestion: "Mission hero, impact numbers, stories, donation CTA.", componentSuggestion: "Impact cards, story tiles, donation panel, volunteer CTA." }
];

export const defaultWebsiteType = websiteTypes[0];
